Feature: Auth flow
yellorg/website pull request #226
Opened 2022-08-05 12:01 UTC by chumaknadya

2022-08-08 08:16 UTC, akhlopiachyi commented on hooks/useSocialSession.ts
> +        });
please be sure there is a method to remove this listener when component will be unmounted (in case this listener is mandatory)

2022-08-08 08:18 UTC, akhlopiachyi commented on components/Duckies/DuckiesEarnMore/index.tsx
> -    const triedToEagerConnect = useEagerConnect();
please make sure, when you have connected metamask and refresh the page you will have connected metamask account

2022-08-08 08:19 UTC, akhlopiachyi commented on components/Duckies/DuckiesHero/index.tsx
> -    const triedToEagerConnect = useEagerConnect();
please make sure, when you have connected metamask and refresh the page you will have connected metamask account

2022-08-08 08:21 UTC, akhlopiachyi approved these changes

2022-08-08 09:27 UTC, MaxMoskalenko commented on components/Duckies/DuckiesEarnMore/index.tsx
> -    const triedToEagerConnect = useEagerConnect();
Page is connected to metamask via useMetaMask hook (it has useEagerConnect inside)

2022-08-10 14:38 UTC, mod requested changes
Comment, better take them into consideration using comments in code.
No need to resolve all comment to merge.

2022-08-10 14:38 UTC, mod commented on .drone.yml
> +      METAMASK_PRIVATE_KEY:
A server side private key has nothing to do with Metamask
maybe just SERVER_PRIVATE_KEY

2022-08-10 14:38 UTC, mod commented on .env.example
> +JWT_PRIVATE_KEY=changeme
maybe GOTRUE_JWT_SECRET ?
isn't it a shared secret and not a key

2022-08-10 14:38 UTC, mod commented on .env.production
> +METAMASK_PRIVATE_KEY=APP_NEXT_METAMASK_PRIVATE_KEY
are we 100% sure this will not be in Bundle or something?

2022-08-10 14:38 UTC, mod commented on features/users/userApi.ts
> +import { setIsSessionCookie } from '../globals/globalsSlice';
what's a feature, why is it API
why this code isn't with the API in pages/api/
should this code be protected?

I recommend wrapping supabase/supabase-js in our own Session lib. object

2022-08-10 14:38 UTC, mod commented on pages/api/v2/private/referral/referral_token.ts
> +    const provider = new ethers.providers.JsonRpcProvider(
why backend need the polygon json rpc?

2022-08-10 14:38 UTC, mod commented on pages/api/v2/private/referral/referral_token.ts
> +    const decimals = await contract.decimals();
this seems very slow and overkill, we request it at every transaction, you need to add comment
//FIXME: Remove due to performance

Maybe server can fetch once and start, we should also initialize all variables at one place.

2022-08-10 14:38 UTC, mod commented on pages/api/v2/private/users/me.ts
> +    const userId = getUserFromCookies(req.cookies).sub;
I am afraid there is no cookie session here, only a JWT in HTTP header,
where is coming the cookie from

2022-08-10 14:38 UTC, mod commented on scripts/generateRsaKeyPair.js
> +const crypto = require('crypto');
RSA uppercase

2022-08-10 14:38 UTC, mod commented on pages/api/v2/public/setSessionCookie.ts
> +    supabase.auth.api.setAuthCookie(req, res);
I am not familiar with cookies in gotrue

2022-08-10 14:42 UTC, akhlopiachyi commented on .drone.yml
> +      METAMASK_PRIVATE_KEY:
This is metamask private key to sign transactions

2022-08-10 14:45 UTC, akhlopiachyi commented on .env.production
> +METAMASK_PRIVATE_KEY=APP_NEXT_METAMASK_PRIVATE_KEY
Yes, we do
If env starts without NEXT_PUBLIC -> it will not be exposed to the browser

2022-08-10 16:44 UTC, mod commented on .drone.yml
> +      METAMASK_PRIVATE_KEY:
metamask is a browser plugin, there is nothing related to metamask in the backend

2022-08-10 16:46 UTC, mod commented on .env.production
> +METAMASK_PRIVATE_KEY=APP_NEXT_METAMASK_PRIVATE_KEY
what's APP_NEXT_JWT_PRIVATE_KEY it's a placeholder to replace with value ?

2022-08-11 12:28 UTC, chumaknadya commented on helpers/getUserFromDatabase.ts
> +        .select('*, phones(*), wallets(*)')
here it should be only with '*'

Don't want to load user with all that data on each function call

In case of need we will load user address or phone

2022-08-11 12:35 UTC, chumaknadya commented on .drone.yml
> +      METAMASK_PRIVATE_KEY:
@akhlopiachyi where we use that key?

2022-08-11 12:36 UTC, chumaknadya commented on .env.example
> +JWT_PRIVATE_KEY=changeme
Let's put TODO here to manage all envs question later

2022-08-11 12:39 UTC, chumaknadya commented on config/database.json
> -			"ENV": "TEST_DATABASE_USER"
@MaxMoskalenko could you check whether we can inherit those configs from one 

Just to not double write those cars in each stage

2022-08-11 12:40 UTC, chumaknadya commented on helpers/getSignatureMessage.ts
> +        secret: jwtPrivateKey,
Remove secret from here

2022-08-11 12:51 UTC, chumaknadya commented on pages/api/v2/private/users/me.ts
> +        const data = await getUserFromDatabase(userId);
Do we really need information about users phones and wallets here?

If not, return current_user with fields like we have in DB

2022-08-11 12:59 UTC, akhlopiachyi commented on .drone.yml
> +      METAMASK_PRIVATE_KEY:
In signing transactions:
- https://github.com/yellorg/website/blob/feature/db-auth/pages/api/v2/private/tx/referral.ts
- https://github.com/yellorg/website/blob/feature/db-auth/pages/api/v2/private/tx/bountyAll.ts
- https://github.com/yellorg/website/blob/feature/db-auth/pages/api/v2/private/tx/referral.ts

2022-08-11 13:02 UTC, akhlopiachyi commented on .env.example
> +JWT_PRIVATE_KEY=changeme
This JWT private key is a key to encode/decode jwt with referral token:
- https://github.com/yellorg/website/blob/feature/db-auth/pages/api/v2/private/referral/referral_token.ts
- https://github.com/yellorg/website/blob/feature/db-auth/pages/api/v2/private/referral/save_referral.ts

2022-08-11 13:02 UTC, akhlopiachyi commented on .env.production
> +METAMASK_PRIVATE_KEY=APP_NEXT_METAMASK_PRIVATE_KEY
Yes, APP_NEXT_* are placeholders that are changed during the build with secrets or runtime envs

2022-08-11 13:48 UTC, MaxMoskalenko commented on config/database.json
> -			"ENV": "TEST_DATABASE_USER"
If configs are the same for all environments and we don`t really use them, then these settings could be reduced to one default setting set

2022-08-12 17:55 UTC, MaxMoskalenko commented on helpers/getUserFromCookies.ts
> +    //FIXME centralize variable in a single place don't access via ENV if JWT_SECRET is empty application should not start
How to do that? process.env is already looks centralized

2022-08-12 17:55 UTC, MaxMoskalenko commented on pages/api/v2/private/users/generate_hash.ts
> +    //FIXME move nonce inside jwt, use "iat" and "jti", iat will be just unixtimestamp in seconds, jti will be a random number base64 size 8 char max
where will we get jti for regenerating hash message?

2022-08-12 17:55 UTC, MaxMoskalenko commented on pages/api/v2/private/users/validate_signature.ts
> +    //TODO verify that iat is not older than 30 seconds call it tokenExpireTime / TOKEN_EXPIRE_TIME
If jwt was signed, we cannot restore it with public key. So, some of this verification will be not so clear

2022-08-12 17:55 UTC, mod commented on helpers/getUserFromCookies.ts
> +    const jwtData = jwt.verify(token, process.env.JWT_SECRET || '');
I don't mind verify twice especially if middleware verify from header, and getUser take from cookie
@akhlopiachyi TODO
it doesn't seem you verify jwt is valid, make sure to force JWT_SECRET cannot be null at start `|| '')`  is a very bad practice.

I would suggest we merge getUserFromCookie and getUserFromData
because we want to verify that user exists in database and is not blocked / banned later

we can also save current_user and set it so it's easy to access in the code

if this method fail we can somehow through an accepting we catch in the middleware or somewhere we can return user to page 403.

2022-08-12 18:03 UTC, mod commented on helpers/getUserFromCookies.ts
> +    //FIXME centralize variable in a single place don't access via ENV if JWT_SECRET is empty application should not start
This FIXME is for after merge, ignore for now, @chumaknadya will explain

2022-08-12 18:04 UTC, mod commented on pages/api/v2/private/users/generate_hash.ts
> +    //FIXME move nonce inside jwt, use "iat" and "jti", iat will be just unixtimestamp in seconds, jti will be a random number base64 size 8 char max
you need to pass it back, like iat+jti
only email he should not pass it and get from session

2022-08-12 18:05 UTC, mod commented on pages/api/v2/private/users/validate_signature.ts
> +    //TODO verify that iat is not older than 30 seconds call it tokenExpireTime / TOKEN_EXPIRE_TIME
you need to read more about JWT
there is 3 piece of data, header, body, signature.

2022-08-12 18:06 UTC, mod commented on scripts/generateRsaKeyPair.js
> +const crypto = require('crypto');
Actually why we have this script we don't have RSA keys
we need a helper to generate ECDSA Key for SERVER_PRIVATE_KEY

2022-08-15 12:10 UTC, mod commented on .env.example
> +JWT_PRIVATE_KEY=changeme
this is not a privqate key, but a SHARED_SECRET

2022-08-15 12:53 UTC, mod requested changes

2022-08-15 12:53 UTC, mod commented on helpers/getChallengeMessage.ts
> +        .sign(jwtPrivateKey);
if you are using ECDSA key then algo is ES256
normally this code is not suppose to work
you are using a private_key_pair as a shared secret

2022-08-15 12:53 UTC, mod commented on pages/api/v2/private/referral/referral_token.ts
> +    const jwtPrivateKey = createSecretKey(process.env.JWT_PRIVATE_KEY || '', 'utf-8');
I don't understand why there is UTF-8

2022-08-15 14:04 UTC, mod requested changes

2022-08-15 14:04 UTC, mod commented on pages/api/v2/private/referral/referral_token.ts
> +    const jwtPrivateKey = createSecretKey(process.env.JWT_PRIVATE_KEY || '', 'utf-8');
use the same SERVER_PRIVATE_KEY with EC256

2022-08-15 14:10 UTC, mod commented on pages/api/v2/private/referral/referral_token.ts
> +        .sign(jwtPrivateKey);
const jwtToken = await new SignJWT(payload)
        .setProtectedHeader({ alg: 'ES256' })
        .sign(SERVER_PRIVATE_KEY);

2022-08-15 14:19 UTC, mod commented on pages/api/v2/private/referral/referral_token.ts
> +    const jwtPrivateKey = createSecretKey(process.env.JWT_PRIVATE_KEY || '', 'utf-8');
const jwtToken = await new SignJWT(payload)
    .setProtectedHeader({ alg: 'ES256' })
    .sign(SERVER_PRIVATE_KEY);

2022-08-16 09:29 UTC, mod approved these changes

2022-08-16 09:31 UTC, merged