Add Tokenomics block
yellorg/website pull request #27
Opened 2021-09-23 18:24 UTC by kh-ruslan

2021-09-23 18:55 UTC, lckmidnight requested changes
Please:

- [ ] Take care of responsiveness of the block: the image does not position correctly on lower body width.
- [ ] Rename `Tokenomics.js` to `index.js` and `Tokenomics.scss` to `styles.scss`, in order to match other components naming convention.

2021-09-23 18:55 UTC, lckmidnight commented on src/components/Tokenomics/Tokenomics.js
> +                                >
```suggestion
                                <div
                                    key={title}
                                    className={`tokenomics__pie-chart--item  ${className}`}
                                >
```

2021-09-24 07:26 UTC, jengjeng commented
@kh-ruslan pls check the breakpoint to be the same with http://yellow.org/

2021-09-24 09:01 UTC, josadcha requested changes

2021-09-24 09:01 UTC, josadcha commented on src/components/Tokenomics/index.js
> +                                    to="/docs/overview/what-is-xln"
please change link to `/docs/concepts/architecture`

2021-09-24 09:01 UTC, josadcha commented on src/components/Tokenomics/index.js
> +                        <span className="subtitle-with-bg-primary subtitle-2-18-700">
use` .highlight` class instead, remove styles for this class

2021-09-24 09:28 UTC, josadcha approved these changes

2021-09-24 09:29 UTC, merged