feat(duckies): Add locking and banning in Duckies SC
yellorg/website pull request #98
Opened 2022-07-08 11:01 UTC by jengjeng

2022-07-08 11:38 UTC, mod commented on contracts/contracts/Duckies.sol
>  import "@openzeppelin/contracts-upgradeable/access/OwnableUpgradeable.sol";
As the documentation suggest you don't combine Ownable and Access control.

2022-07-08 11:44 UTC, mod commented on contracts/contracts/Duckies.sol
> +    // Account Locking
ROLE_SUPERADMIN (All)
ROLE_MODERATOR (lock/unlock)
ROLE_SUPERVISOR (lock/unlock,ban/unban)
ROLE_LOCKED
ROLE_BANNED

2022-07-11 03:55 UTC, jengjeng commented on contracts/contracts/Duckies.sol
> +    // Account Locking
Is it possible to change the convention name to {ROLE_NAME}_ROLE instead of ROLE_{ROLENAME}?
to make it follows the same convention as others.
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/presets/ERC20PresetMinterPauser.sol#L29

2022-07-14 04:24 UTC, calj commented
can we use a uint32 for the affiliate array?

2022-07-14 17:30 UTC, akhlopiachyi approved these changes

2022-07-14 17:56 UTC, mod commented on contracts/contracts/Duckies.sol
> +    // Account Locking
Sure

2022-07-15 04:23 UTC, jengjeng commented on contracts/contracts/Duckies.sol
> +    // Account Locking
so I did the access control to be permission-based (locker, banner) instead of role-based (moderator, supervisor) to make it flexible to manage later.

2022-07-18 15:49 UTC, mod requested changes
I'm not confortable if the inheritance I don't really feel like it help,
I'm still considering it until deployment

2022-07-19 05:23 UTC, jengjeng commented
> I'm not confortable if the inheritance I don't really feel like it help, I'm still considering it until deployment
@mod 
I would like to separate the logic of ERC20, Security (Lock&Ban), and Tokenomic into each file instead of mixing everything in 1 file.
so `Duckies.sol` can focus on their tokenomic and some custom features it needed.

2022-07-19 05:30 UTC, jengjeng commented on contracts/contracts/Duckies.sol
if you meant `_mint` function, it is necessary that solidity is required to override how a function in the parent contract is implemented in the derived class if it has the same function name and parameters. otherwise, the compiler will raise an error.

`
TypeError: Derived contract must override function "_mint". Two or more base classes define function with same name and parameter types.
`

2022-08-16 16:55 UTC, closed without merging